package com.turing.skyeyes.entity;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.Date;


@Builder
@Setter
@Getter
public class TCdHouseTradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.id
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.data_date
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Date dataDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.urban_new_house_num
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Integer urbanNewHouseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.urban_new_house_are
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private BigDecimal urbanNewHouseAre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.country_new_house_num
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Integer countryNewHouseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.country_new_house_area
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private BigDecimal countryNewHouseArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.urban_old_house_num
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Integer urbanOldHouseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.urban_old_house_are
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private BigDecimal urbanOldHouseAre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.country_old_house_num
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private Integer countryOldHouseNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cd_house_trade_info.country_old_house_are
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    private BigDecimal countryOldHouseAre;


}