package com.turing.skyeyes.mapper;

import com.turing.skyeyes.entity.TCdHouseTradeInfo;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface TCdHouseTradeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cd_house_trade_info
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cd_house_trade_info
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    int insert(TCdHouseTradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cd_house_trade_info
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    TCdHouseTradeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cd_house_trade_info
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    List<TCdHouseTradeInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cd_house_trade_info
     *
     * @mbggenerated Mon Feb 06 22:35:49 SGT 2023
     */
    int updateByPrimaryKey(TCdHouseTradeInfo record);
}